// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  blog_post: dynamic(() => import("./BlogPost")),
  blog_text: dynamic(() => import("./BlogText")),
  contact_form: dynamic(() => import("./ContactForm")),
  hero: dynamic(() => import("./HomeHero")),
  image_full: dynamic(() => import("./ImageFull")),
  images: dynamic(() => import("./Images")),
  item: dynamic(() => import("./Item")),
  rich_text: dynamic(() => import("./RichText")),
  steps: dynamic(() => import("./Steps")),
  text_image: dynamic(() => import("./TextImage")),
  works: dynamic(() => import("./Works")),
  youtube: dynamic(() => import("./Youtube")),
};
